services:
  pythonbackend:
    image: shafiqninaba/fyp:backend-1.0
    depends_on:
      - mysql
    ports:
      - "8080:8080"
  pythonapp:
    image: shafiqninaba/fyp:app-1.0
    depends_on:
      - mysql
    ports:
      - "5000:5000"
  mysql:
    image: shafiqninaba/fyp:sql-1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'masked_recognition'
    ports:
      - "3306:3306"
